const BEN10_DATA = [
  {
    "id": "alienx",
    "name": "Alien X",
    "species": "Celestialsapien",
    "intelligence": 100,
    "strength": 100,
    "speed": 100,
    "durability": 100,
    "power": 100,
    "combat": 100,
    "tier": 10.33,
    "imageUrl": "images/alienx.jpg",
    "detailUrl": "https://www.superherodb.com/alien-x/10-10987/"
  },
  {
    "id": "ampfibian",
    "name": "AmpFibian",
    "species": "Amperi",
    "intelligence": 70,
    "strength": 25,
    "speed": 50,
    "durability": 40,
    "power": 75,
    "combat": 50,
    "tier": 3.66,
    "imageUrl": "images/ampfibian.jpg",
    "detailUrl": "https://www.superherodb.com/ampfibian/10-22146/"
  },
  {
    "id": "arctiguana",
    "name": "Arctiguana",
    "species": "Polar Manzardill",
    "intelligence": 50,
    "strength": 25,
    "speed": 25,
    "durability": 40,
    "power": 50,
    "combat": 60,
    "tier": 2,
    "imageUrl": "images/arctiguana.jpg",
    "detailUrl": "https://www.superherodb.com/arctiguana/10-22147/"
  },
  {
    "id": "armodrillo",
    "name": "Armodrillo",
    "species": "Talpaedan",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 60,
    "power": 70,
    "combat": 70,
    "tier": 4.33,
    "imageUrl": "images/armodrillo.jpg",
    "detailUrl": "https://www.superherodb.com/armodrillo/10-22148/"
  },
  {
    "id": "astrodactyl",
    "name": "Astrodactyl",
    "species": "Unknown",
    "intelligence": 50,
    "strength": 25,
    "speed": 100,
    "durability": 40,
    "power": 70,
    "combat": 50,
    "tier": 2.33,
    "imageUrl": "images/astrodactyl.jpg",
    "detailUrl": "https://www.superherodb.com/astrodactyl/10-22149/"
  },
  {
    "id": "atomix",
    "name": "Atomix",
    "species": "Unknown",
    "intelligence": 75,
    "strength": 100,
    "speed": 100,
    "durability": 90,
    "power": 100,
    "combat": 90,
    "tier": 5.66,
    "imageUrl": "images/atomix.jpg",
    "detailUrl": "https://www.superherodb.com/atomix/10-20701/"
  },
  {
    "id": "ballweevil",
    "name": "Ball Weevil",
    "species": "Unknown",
    "intelligence": 50,
    "strength": 5,
    "speed": 25,
    "durability": 20,
    "power": 50,
    "combat": 50,
    "tier": 1.66,
    "imageUrl": "images/ballweevil.jpg",
    "detailUrl": "https://www.superherodb.com/ball-weevil/10-22150/"
  },
  {
    "id": "bigchill",
    "name": "Big Chill",
    "species": "Necrofriggian",
    "intelligence": 70,
    "strength": 50,
    "speed": 75,
    "durability": 40,
    "power": 85,
    "combat": 80,
    "tier": 4.66,
    "imageUrl": "images/bigchill.jpg",
    "detailUrl": "https://www.superherodb.com/big-chill/10-20857/"
  },
  {
    "id": "blitzwolfer",
    "name": "Blitzwolfer",
    "species": "Loboan",
    "intelligence": 50,
    "strength": 30,
    "speed": 50,
    "durability": 40,
    "power": 50,
    "combat": 95,
    "tier": 2,
    "imageUrl": "images/blitzwolfer.jpg",
    "detailUrl": "https://www.superherodb.com/blitzwolfer/10-21982/"
  },
  {
    "id": "bloxx",
    "name": "Bloxx",
    "species": "Segmentasapien",
    "intelligence": 50,
    "strength": 25,
    "speed": 25,
    "durability": 45,
    "power": 65,
    "combat": 70,
    "tier": 2.33,
    "imageUrl": "images/bloxx.jpg",
    "detailUrl": "https://www.superherodb.com/bloxx/10-22151/"
  },
  {
    "id": "brainstorm",
    "name": "Brainstorm",
    "species": "Cerebrocrustacean",
    "intelligence": 100,
    "strength": 25,
    "speed": 25,
    "durability": 45,
    "power": 70,
    "combat": 65,
    "tier": 3.66,
    "imageUrl": "images/brainstorm.jpg",
    "detailUrl": "https://www.superherodb.com/brainstorm/10-20858/"
  },
  {
    "id": "bullfrag",
    "name": "Bullfrag",
    "species": "Incursean",
    "intelligence": 50,
    "strength": 55,
    "speed": 25,
    "durability": 40,
    "power": 45,
    "combat": 95,
    "tier": 1.66,
    "imageUrl": "images/bullfrag.jpg",
    "detailUrl": "https://www.superherodb.com/bullfrag/10-22152/"
  },
  {
    "id": "buzzshock",
    "name": "Buzzshock",
    "species": "Nosedeenian",
    "intelligence": 50,
    "strength": 1,
    "speed": 75,
    "durability": 11,
    "power": 65,
    "combat": 19,
    "tier": 1.66,
    "imageUrl": "images/buzzshock.jpg",
    "detailUrl": "https://www.superherodb.com/buzzshock/10-22153/"
  },
  {
    "id": "cannonbolt",
    "name": "Cannonbolt",
    "species": "Arburian Pelarota",
    "intelligence": 50,
    "strength": 90,
    "speed": 50,
    "durability": 60,
    "power": 70,
    "combat": 60,
    "tier": 4.33,
    "imageUrl": "images/cannonbolt.jpg",
    "detailUrl": "https://www.superherodb.com/cannonbolt/10-20859/"
  },
  {
    "id": "chamalien",
    "name": "Chamalien",
    "species": "Merlinisapien",
    "intelligence": 50,
    "strength": 55,
    "speed": 25,
    "durability": 30,
    "power": 35,
    "combat": 65,
    "tier": 1.33,
    "imageUrl": "images/chamalien.jpg",
    "detailUrl": "https://www.superherodb.com/chamalien/10-22154/"
  },
  {
    "id": "chromastone",
    "name": "Chromastone",
    "species": "Crystalsapien",
    "intelligence": 70,
    "strength": 100,
    "speed": 100,
    "durability": 75,
    "power": 90,
    "combat": 85,
    "tier": 4.66,
    "imageUrl": "images/chromastone.jpg",
    "detailUrl": "https://www.superherodb.com/chromastone/10-20860/"
  },
  {
    "id": "clockwork",
    "name": "Clockwork",
    "species": "Chronosapien",
    "intelligence": 75,
    "strength": 25,
    "speed": 100,
    "durability": 15,
    "power": 100,
    "combat": 35,
    "tier": 8,
    "imageUrl": "images/clockwork.jpg",
    "detailUrl": "https://www.superherodb.com/clockwork/10-20035/"
  },
  {
    "id": "crashhopper",
    "name": "Crashhopper",
    "species": "Orthopterran",
    "intelligence": 50,
    "strength": 25,
    "speed": 50,
    "durability": 40,
    "power": 45,
    "combat": 80,
    "tier": 1.66,
    "imageUrl": "images/crashhopper.jpg",
    "detailUrl": "https://www.superherodb.com/crashhopper/10-22155/"
  },
  {
    "id": "diamondhead",
    "name": "Diamondhead",
    "species": "Petrosapien",
    "intelligence": 60,
    "strength": 100,
    "speed": 25,
    "durability": 75,
    "power": 85,
    "combat": 90,
    "tier": 4.66,
    "imageUrl": "images/diamondhead.jpg",
    "detailUrl": "https://www.superherodb.com/diamondhead/10-20861/"
  },
  {
    "id": "ditto",
    "name": "Ditto",
    "species": "Splixson",
    "intelligence": 50,
    "strength": 1,
    "speed": 17,
    "durability": 11,
    "power": 30,
    "combat": 50,
    "tier": 1,
    "imageUrl": "images/ditto.jpg",
    "detailUrl": "https://www.superherodb.com/ditto/10-21576/"
  },
  {
    "id": "eatle",
    "name": "Eatle",
    "species": "Oryctini",
    "intelligence": 50,
    "strength": 85,
    "speed": 25,
    "durability": 60,
    "power": 70,
    "combat": 70,
    "tier": 4.33,
    "imageUrl": "images/eatle.jpg",
    "detailUrl": "https://www.superherodb.com/eatle/10-22156/"
  },
  {
    "id": "echoeecho",
    "name": "Echo Echo",
    "species": "Sonorossian",
    "intelligence": 50,
    "strength": 14,
    "speed": 25,
    "durability": 20,
    "power": 65,
    "combat": 70,
    "tier": 3.66,
    "imageUrl": "images/echoeecho.jpg",
    "detailUrl": "https://www.superherodb.com/echo-echo/10-20862/"
  },
  {
    "id": "eyeguy",
    "name": "Eye Guy",
    "species": "Opticoid",
    "intelligence": 50,
    "strength": 25,
    "speed": 25,
    "durability": 40,
    "power": 60,
    "combat": 70,
    "tier": 2,
    "imageUrl": "images/eyeguy.jpg",
    "detailUrl": "https://www.superherodb.com/eye-guy/10-21983/"
  },
  {
    "id": "fasttrack",
    "name": "Fasttrack",
    "species": "Citrakayah",
    "intelligence": 50,
    "strength": 30,
    "speed": 90,
    "durability": 40,
    "power": 45,
    "combat": 80,
    "tier": 1.66,
    "imageUrl": "images/fasttrack.jpg",
    "detailUrl": "https://www.superherodb.com/fasttrack/10-22157/"
  },
  {
    "id": "feedback",
    "name": "Feedback",
    "species": "Conductoid",
    "intelligence": 50,
    "strength": 100,
    "speed": 100,
    "durability": 100,
    "power": 100,
    "combat": 85,
    "tier": 8,
    "imageUrl": "images/feedback.jpg",
    "detailUrl": "https://www.superherodb.com/feedback/10-20863/"
  },
  {
    "id": "fourarms",
    "name": "Four Arms",
    "species": "Tetramand",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 55,
    "power": 70,
    "combat": 95,
    "tier": 4.33,
    "imageUrl": "images/fourarms.jpg",
    "detailUrl": "https://www.superherodb.com/four-arms/10-20865/"
  },
  {
    "id": "frankenstrike",
    "name": "Frankenstrike",
    "species": "Transylian",
    "intelligence": 50,
    "strength": 85,
    "speed": 25,
    "durability": 50,
    "power": 75,
    "combat": 65,
    "tier": 4,
    "imageUrl": "images/frankenstrike.jpg",
    "detailUrl": "https://www.superherodb.com/frankenstrike/10-21984/"
  },
  {
    "id": "ghostfreak",
    "name": "Ghostfreak",
    "species": "Ectonurite",
    "intelligence": 60,
    "strength": 50,
    "speed": 25,
    "durability": 40,
    "power": 90,
    "combat": 50,
    "tier": 4.66,
    "imageUrl": "images/ghostfreak.jpg",
    "detailUrl": "https://www.superherodb.com/ghostfreak/10-20866/"
  },
  {
    "id": "goop",
    "name": "Goop",
    "species": "Polymorph",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 40,
    "power": 65,
    "combat": 70,
    "tier": 4,
    "imageUrl": "images/goop.jpg",
    "detailUrl": "https://www.superherodb.com/goop/10-20867/"
  },
  {
    "id": "gravattack",
    "name": "Gravattack",
    "species": "Galilean",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 75,
    "power": 85,
    "combat": 45,
    "tier": 4.66,
    "imageUrl": "images/gravattack.jpg",
    "detailUrl": "https://www.superherodb.com/gravattack/10-22158/"
  },
  {
    "id": "greymatter",
    "name": "Grey Matter",
    "species": "Galvan",
    "intelligence": 100,
    "strength": 1,
    "speed": 6,
    "durability": 5,
    "power": 11,
    "combat": 5,
    "tier": 0,
    "imageUrl": "images/greymatter.jpg",
    "detailUrl": "https://www.superherodb.com/grey-matter/10-20868/"
  },
  {
    "id": "gutrot",
    "name": "Gutrot",
    "species": "Unknown",
    "intelligence": 90,
    "strength": 25,
    "speed": 14,
    "durability": 35,
    "power": 50,
    "combat": 15,
    "tier": 1.33,
    "imageUrl": "images/gutrot.jpg",
    "detailUrl": "https://www.superherodb.com/gutrot/10-22159/"
  },
  {
    "id": "heatblast",
    "name": "Heatblast",
    "species": "Pyronite",
    "intelligence": 50,
    "strength": 55,
    "speed": 80,
    "durability": 45,
    "power": 85,
    "combat": 75,
    "tier": 4.33,
    "imageUrl": "images/heatblast.jpg",
    "detailUrl": "https://www.superherodb.com/heatblast/10-20869/"
  },
  {
    "id": "humungousaur",
    "name": "Humungousaur",
    "species": "Vaxasaurian",
    "intelligence": 50,
    "strength": 100,
    "speed": 20,
    "durability": 55,
    "power": 70,
    "combat": 60,
    "tier": 4.66,
    "imageUrl": "images/humungousaur.jpg",
    "detailUrl": "https://www.superherodb.com/humungosaur/10-20870/"
  },
  {
    "id": "jetray",
    "name": "Jetray",
    "species": "Aerophibian",
    "intelligence": 50,
    "strength": 50,
    "speed": 100,
    "durability": 40,
    "power": 75,
    "combat": 45,
    "tier": 4.33,
    "imageUrl": "images/jetray.jpg",
    "detailUrl": "https://www.superherodb.com/jetray/10-20871/"
  },
  {
    "id": "juryrigg",
    "name": "Jury Rigg",
    "species": "Planchakule",
    "intelligence": 90,
    "strength": 1,
    "speed": 25,
    "durability": 9,
    "power": 25,
    "combat": 25,
    "tier": 1,
    "imageUrl": "images/juryrigg.jpg",
    "detailUrl": "https://www.superherodb.com/juryrigg/10-22160/"
  },
  {
    "id": "kickinhawk",
    "name": "Kickin Hawk",
    "species": "Unknown",
    "intelligence": 50,
    "strength": 25,
    "speed": 30,
    "durability": 40,
    "power": 45,
    "combat": 100,
    "tier": 1.66,
    "imageUrl": "images/kickinhawk.jpg",
    "detailUrl": "https://www.superherodb.com/kickin-hawk/10-22161/"
  },
  {
    "id": "lodestar",
    "name": "Lodestar",
    "species": "Biosovortian",
    "intelligence": 60,
    "strength": 50,
    "speed": 25,
    "durability": 45,
    "power": 75,
    "combat": 50,
    "tier": 3.66,
    "imageUrl": "images/lodestar.jpg",
    "detailUrl": "https://www.superherodb.com/lodestar/10-22006/"
  },
  {
    "id": "molestache",
    "name": "Mole-Stache",
    "species": "Unknown",
    "intelligence": 55,
    "strength": 25,
    "speed": 20,
    "durability": 20,
    "power": 25,
    "combat": 50,
    "tier": 1,
    "imageUrl": "images/molestache.jpg",
    "detailUrl": "https://www.superherodb.com/mole-stache/10-22162/"
  },
  {
    "id": "nanomech",
    "name": "Nanomech",
    "species": "Nanochip",
    "intelligence": 50,
    "strength": 1,
    "speed": 8,
    "durability": 1,
    "power": 5,
    "combat": 1,
    "tier": 0,
    "imageUrl": "images/nanomech.jpg",
    "detailUrl": "https://www.superherodb.com/nanomech/10-21007/"
  },
  {
    "id": "nrg",
    "name": "NRG",
    "species": "Prypiatosian-B",
    "intelligence": 55,
    "strength": 90,
    "speed": 50,
    "durability": 75,
    "power": 85,
    "combat": 40,
    "tier": 4.66,
    "imageUrl": "images/nrg.jpg",
    "detailUrl": "https://www.superherodb.com/nrg/10-22163/"
  },
  {
    "id": "peskydust",
    "name": "Pesky Dust",
    "species": "Nemuina",
    "intelligence": 50,
    "strength": 1,
    "speed": 25,
    "durability": 10,
    "power": 45,
    "combat": 10,
    "tier": 1.33,
    "imageUrl": "images/peskydust.jpg",
    "detailUrl": "https://www.superherodb.com/pesky-dust/10-22164/"
  },
  {
    "id": "rath",
    "name": "Rath",
    "species": "Appoplexian",
    "intelligence": 35,
    "strength": 100,
    "speed": 30,
    "durability": 55,
    "power": 60,
    "combat": 95,
    "tier": 3.66,
    "imageUrl": "images/rath.jpg",
    "detailUrl": "https://www.superherodb.com/rath/10-20873/"
  },
  {
    "id": "ripjaws",
    "name": "Ripjaws",
    "species": "Piscciss Volann",
    "intelligence": 50,
    "strength": 55,
    "speed": 55,
    "durability": 40,
    "power": 45,
    "combat": 50,
    "tier": 1.66,
    "imageUrl": "images/ripjaws.jpg",
    "detailUrl": "https://www.superherodb.com/ripjaws/10-21985/"
  },
  {
    "id": "shocksquatch",
    "name": "Shocksquatch",
    "species": "Gimlinopithecus",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 55,
    "power": 70,
    "combat": 75,
    "tier": 3.66,
    "imageUrl": "images/shocksquatch.jpg",
    "detailUrl": "https://www.superherodb.com/shocksquatch/10-22165/"
  },
  {
    "id": "snareoh",
    "name": "Snare-Oh",
    "species": "Thep Khufan",
    "intelligence": 50,
    "strength": 25,
    "speed": 25,
    "durability": 40,
    "power": 65,
    "combat": 85,
    "tier": 2,
    "imageUrl": "images/snareoh.jpg",
    "detailUrl": "https://www.superherodb.com/snare-oh/10-21986/"
  },
  {
    "id": "spidermonkey",
    "name": "Spidermonkey",
    "species": "Arachnichimp",
    "intelligence": 50,
    "strength": 30,
    "speed": 25,
    "durability": 30,
    "power": 45,
    "combat": 90,
    "tier": 1.66,
    "imageUrl": "images/spidermonkey.jpg",
    "detailUrl": "https://www.superherodb.com/spidermonkey/10-20875/"
  },
  {
    "id": "spitter",
    "name": "Spitter",
    "species": "Sphoeroid",
    "intelligence": 50,
    "strength": 25,
    "speed": 25,
    "durability": 30,
    "power": 30,
    "combat": 35,
    "tier": 1.33,
    "imageUrl": "images/spitter.jpg",
    "detailUrl": "https://www.superherodb.com/spitter/10-22166/"
  },
  {
    "id": "stinkfly",
    "name": "Stinkfly",
    "species": "Lepidopterran",
    "intelligence": 50,
    "strength": 30,
    "speed": 70,
    "durability": 40,
    "power": 45,
    "combat": 50,
    "tier": 1.66,
    "imageUrl": "images/stinkfly.jpg",
    "detailUrl": "https://www.superherodb.com/stinkfly/10-21987/"
  },
  {
    "id": "swampfire",
    "name": "Swampfire",
    "species": "Methanosian",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 50,
    "power": 85,
    "combat": 80,
    "tier": 4.33,
    "imageUrl": "images/swampfire.jpg",
    "detailUrl": "https://www.superherodb.com/swampfire/10-20877/"
  },
  {
    "id": "terraspin",
    "name": "Terraspin",
    "species": "Geochelone Aerio",
    "intelligence": 50,
    "strength": 30,
    "speed": 25,
    "durability": 40,
    "power": 45,
    "combat": 50,
    "tier": 1.66,
    "imageUrl": "images/terraspin.jpg",
    "detailUrl": "https://www.superherodb.com/terraspin/10-22167/"
  },
  {
    "id": "theworst",
    "name": "The Worst",
    "species": "Atrocian",
    "intelligence": 50,
    "strength": 1,
    "speed": 1,
    "durability": 75,
    "power": 1,
    "combat": 1,
    "tier": 0,
    "imageUrl": "images/theworst.jpg",
    "detailUrl": "https://www.superherodb.com/the-worst/10-22168/"
  },
  {
    "id": "toepick",
    "name": "Toepick",
    "species": "Unknown",
    "intelligence": 50,
    "strength": 25,
    "speed": 6,
    "durability": 30,
    "power": 30,
    "combat": 10,
    "tier": 1.33,
    "imageUrl": "images/toepick.jpg",
    "detailUrl": "https://www.superherodb.com/toepick/10-22169/"
  },
  {
    "id": "ultimatebigchill",
    "name": "Ultimate Big Chill",
    "species": "Evolved Necrofriggian",
    "intelligence": 70,
    "strength": 55,
    "speed": 80,
    "durability": 40,
    "power": 90,
    "combat": 80,
    "tier": 4.66,
    "imageUrl": "images/ultimatebigchill.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-big-chill/10-21718/"
  },
  {
    "id": "ultimatecannonbolt",
    "name": "Ultimate Cannonbolt",
    "species": "Evolved Arburian Pelarota",
    "intelligence": 50,
    "strength": 90,
    "speed": 50,
    "durability": 60,
    "power": 70,
    "combat": 60,
    "tier": 4.66,
    "imageUrl": "images/ultimatecannonbolt.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-cannonbolt/10-21719/"
  },
  {
    "id": "ultimateechoeecho",
    "name": "Ultimate Echo Echo",
    "species": "Evolved Sonorossian",
    "intelligence": 50,
    "strength": 55,
    "speed": 100,
    "durability": 50,
    "power": 90,
    "combat": 80,
    "tier": 5.66,
    "imageUrl": "images/ultimateechoeecho.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-echo-echo/10-21720/"
  },
  {
    "id": "ultimatehumungousaur",
    "name": "Ultimate Humungousaur",
    "species": "Evolved Vaxasaurian",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 65,
    "power": 85,
    "combat": 60,
    "tier": 4.66,
    "imageUrl": "images/ultimatehumungousaur.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-humungosaur/10-21721/"
  },
  {
    "id": "ultimatespidermonkey",
    "name": "Ultimate Spidermonkey",
    "species": "Evolved Arachnichimp",
    "intelligence": 50,
    "strength": 60,
    "speed": 25,
    "durability": 40,
    "power": 50,
    "combat": 90,
    "tier": 3,
    "imageUrl": "images/ultimatespidermonkey.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-spidermonkey/10-21722/"
  },
  {
    "id": "ultimateswampfire",
    "name": "Ultimate Swampfire",
    "species": "Evolved Methanosian",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 55,
    "power": 90,
    "combat": 80,
    "tier": 4.66,
    "imageUrl": "images/ultimateswampfire.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-swampfire/10-21723/"
  },
  {
    "id": "ultimatewaybig",
    "name": "Ultimate Way Big",
    "species": "Evolved To'kustar",
    "intelligence": 50,
    "strength": 100,
    "speed": 100,
    "durability": 100,
    "power": 100,
    "combat": 90,
    "tier": 6.33,
    "imageUrl": "images/ultimatewaybig.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-way-big/10-21555/"
  },
  {
    "id": "ultimatewildmutt",
    "name": "Ultimate Wildmutt",
    "species": "Evolved Vulpimancer",
    "intelligence": 50,
    "strength": 35,
    "speed": 25,
    "durability": 35,
    "power": 35,
    "combat": 85,
    "tier": 1.66,
    "imageUrl": "images/ultimatewildmutt.jpg",
    "detailUrl": "https://www.superherodb.com/ultimate-wildmutt/10-21724/"
  },
  {
    "id": "upchuck",
    "name": "Upchuck",
    "species": "Gourmand",
    "intelligence": 50,
    "strength": 100,
    "speed": 25,
    "durability": 60,
    "power": 65,
    "combat": 50,
    "tier": 4.66,
    "imageUrl": "images/upchuck.jpg",
    "detailUrl": "https://www.superherodb.com/upchuck/10-21988/"
  },
  {
    "id": "upgrade",
    "name": "Upgrade",
    "species": "Galvanic Mechamorph",
    "intelligence": 60,
    "strength": 85,
    "speed": 25,
    "durability": 50,
    "power": 85,
    "combat": 50,
    "tier": 4.33,
    "imageUrl": "images/upgrade.jpg",
    "detailUrl": "https://www.superherodb.com/upgrade/10-20878/"
  },
  {
    "id": "walkatrout",
    "name": "Walkatrout",
    "species": "Ickthyperambuloid",
    "intelligence": 50,
    "strength": 1,
    "speed": 10,
    "durability": 8,
    "power": 5,
    "combat": 1,
    "tier": 0,
    "imageUrl": "images/walkatrout.jpg",
    "detailUrl": "https://www.superherodb.com/walkatrout/10-22170/"
  },
  {
    "id": "waterhazard",
    "name": "Water Hazard",
    "species": "Orishan",
    "intelligence": 75,
    "strength": 60,
    "speed": 25,
    "durability": 60,
    "power": 45,
    "combat": 70,
    "tier": 1.66,
    "imageUrl": "images/waterhazard.jpg",
    "detailUrl": "https://www.superherodb.com/water-hazard/10-22171/"
  },
  {
    "id": "waybig",
    "name": "Way Big",
    "species": "To'kustar",
    "intelligence": 50,
    "strength": 100,
    "speed": 100,
    "durability": 90,
    "power": 100,
    "combat": 85,
    "tier": 5.66,
    "imageUrl": "images/waybig.jpg",
    "detailUrl": "https://www.superherodb.com/way-big/10-20879/"
  },
  {
    "id": "whampire",
    "name": "Whampire",
    "species": "Vladat",
    "intelligence": 50,
    "strength": 50,
    "speed": 60,
    "durability": 40,
    "power": 85,
    "combat": 80,
    "tier": 4.33,
    "imageUrl": "images/whampire.jpg",
    "detailUrl": "https://www.superherodb.com/whampire/10-22172/"
  },
  {
    "id": "wildmutt",
    "name": "Wildmutt",
    "species": "Vulpimancer",
    "intelligence": 50,
    "strength": 30,
    "speed": 25,
    "durability": 30,
    "power": 35,
    "combat": 85,
    "tier": 1.66,
    "imageUrl": "images/wildmutt.jpg",
    "detailUrl": "https://www.superherodb.com/wildmutt/10-20880/"
  },
  {
    "id": "wildvine",
    "name": "Wildvine",
    "species": "Florauna",
    "intelligence": 50,
    "strength": 55,
    "speed": 25,
    "durability": 40,
    "power": 65,
    "combat": 50,
    "tier": 2,
    "imageUrl": "images/wildvine.jpg",
    "detailUrl": "https://www.superherodb.com/wildvine/10-21989/"
  },
  {
    "id": "xlr8",
    "name": "XLR8",
    "species": "Kineceleran",
    "intelligence": 50,
    "strength": 25,
    "speed": 100,
    "durability": 30,
    "power": 60,
    "combat": 85,
    "tier": 3.66,
    "imageUrl": "images/xlr8.jpg",
    "detailUrl": "https://www.superherodb.com/xlr8/10-20881/"
  }
];
